var config = [{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C1, Definir los requisitos de seguridad :: Qué proyecto de owasp apoya en la definición de estos requisitos?", answers: ["Top ten", "Joomla Vulnerability Scanner Project", "DirBuster", "Application Security Verification Standard"], correct: 4},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C2, Aproveche los Frameworks y Librerias de seguridad :: Cuál de los siguientes CMS ha tenido mas CVEs hasta el 2019", answers: ["Drupal", "Liferay", "Joomla", "Wordpress"], correct: 4},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C3, Acceso seguro a las bases de datos :: Además de asegurar las consultas, debemos enfocar esfuerzos en:", answers: ["Configuraciones seguras", "Autenticación segura", "Comunicaciones seguras", "Todas las anteriores"], correct: 4},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C4, Codificar y escapar los datos :: La codificación de salida contextual es una técnica de programación segura necesaria para detener:", answers: ["sqli", "command injection", "XSS", "Todas las anteriores"], correct: 3},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "A3, Exposición de Datos Sensibles", answers: ["Storing the data", "Streamlining the data", "Proxies the JavaScript file", "All of the mentioned"], correct: 3},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C5, Validar todas las entradas :: Qué patron define la siguiente expresión regular b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}b", answers: ["URL", "correo electronico", "ipv4", "Ninguna de las anteriores"], correct: 3},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C6, Implementar Identidad Digital :: Cuál es la criptonita de superman", answers: ["3707051b4bcdb819 276820b602c6b4b8", "860d35ba29441e1f 89cfb5775ce6696c", "f8f582fd9aa67c19 e542fa2fde6968c7", "84d961568a65073a 3bcf0eb216b2a576"], correct: 4},
{level:"1", theme: "animals", question: "A2, Pérdida de Autenticación", answers: ["Dynamic compression", "Static compression", "Static content", "None of the mentioned"], correct: 2},
{level:"1", theme: "animals", question: ":: C7, Aplicar controles de acceso :: Dentro de los principios de diseño de control de acceso tenemos:", answers: ["Todas las peticiones deben pasar por un check de control de acceso", "Negar por defecto", "Principio de Minimo privilegio", "Todas las anteriores"], correct: 4},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A7, Cross-Site Scripting (XSS) :: Framework para la automatización de ataques XSS  contra aplicaciones web vulnerables del lado del cliente", answers: ["Beef", "Burpsuite", "DirBuster", "Ninguna de las anteriores"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C8, Proteger los datos en todos sus estados :: Los datos  de  tarjetas de credito se deden cifrar en:", answers: ["proceso y reposo", "proceso y  en transito", "en reposo y  en transito", "En todas las anteriores"], correct: 3},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: C9, Implementar registros y monitoreo de eventos :: Cuál de estas no es una ventaja a la hora de implementar este control", answers: ["Garantiza que el usuario es quien dice ser", "Analisis forense e Investigaciones", "Enriqueser los IPS", "Satisfacer cumplimientos regulatorios"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A4, Entidades Externas XML (XXE) :: Un ataque  efectivo con este vector <!ENTITY xxe SYSTEM file:///dev/random>]>, causaria:", answers: ["Salto de Autenticación", "DOS", "robo de información", "modificación de información"], correct: 2},
{level:"1", theme: "animals", question: ":: C10, Controlar todos los errores y excepciones :: Un mal manejo de errores puede llevar a que este tipo de vulnerabilidad se materialice", answers: ["XSS", "DOS", "Perdida de Autenticación", "Ninguna de las anteriores"], correct: 2},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A8, Deserialización Insegura :: Ataques relacionados con la estructura de datos, objetos y manipulación de datos permiten:", answers: ["Ejecución de código remoto", "saltos de control de acceso", "a y b", "Ejecución de código remoto al lado del cliente"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "A10, Registro y Monitoreo Insuficientes :: ", answers: ["1", "3", "5", "7"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A6, Configuración de Seguridad Incorrecta :: Que organización cuenta con puntos de referencia para el hardening de SO, BD y Servidores de App", answers: ["CIS", "MITRE", "a y b", "COSO"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "A5, Pérdida de Control de Acceso :: ", answers: ["Minify", "JavaScript", "Both a and b", "None of the mentioned"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A9, Uso de Componentes con Vulnerabilidades Conocidas :: Uno de los grandes problemas es no contar con:", answers: ["La implementación de guias de hardening sobre los componentes", "Monitoreo sobre las peticiones a los componentes o dependencias", "a y b", "un inventario de versiones de los componentes y dependencias utilizados"], correct: 4},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: ":: A1, Inyección :: ", answers: ["2", "4", "6", "8"], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
{level:"1", theme: "animals", question: "", answers: ["", "", "", ""], correct: 1},
];
